version: "3"

services:
  bookstore-database:
    image: ghcr.io/weijuly/bookstore-database:0.0.1-20220308151403
    networks:
      - bookstore-network
  bookstore-cache:
    image: ghcr.io/weijuly/bookstore-cache:0.0.1-20220308151218
    networks:
      - bookstore-network
  bookstore-service:
    image: ghcr.io/weijuly/bookstore-service:0.0.1-20220308094646
    networks:
      - bookstore-network
    depends_on:
      - bookstore-database
      - bookstore-cache
  bookstore-webapp:
    image: ghcr.io/weijuly/bookstore-webapp:0.0.1-20220429124732
    networks:
      - bookstore-network
    depends_on:
      - bookstore-service
  bookstore-gateway:
    image: ghcr.io/weijuly/bookstore-gateway:0.0.1-20220429125353
    ports:
      - "443:443"
    networks:
      - bookstore-network
    depends_on:
      - bookstore-webapp

networks:
  bookstore-network:
    driver: bridge
