FROM nginx:1.21.6

COPY bookstore-gateway.private.key /etc/ssl/certs/bookstore-gateway.private.key
COPY bookstore-gateway.public.cert /etc/ssl/certs/bookstore-gateway.public.cert

COPY nginx.conf /etc/nginx/nginx.conf

