server:
  port: 8080

graphql:
  specification:
    file: schema.graphqls

spring:
  datasource:
    url: @database.url@
    driverClassName: com.mysql.cj.jdbc.Driver
    username: bookstore
    password: bookstore
    hikari:
      connectionTimeout: 5000
      idleTimeout: 5000
      maxLifetime: 180000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: redis
  redis:
    host: @cache.url@
    port: 6379
    password: bookstore
